
spring:
  application:
    name: $rootProject.name$
  zipkin:
    enabled: false
    base-url: http://localhost:9411
  jackson:
    serialization:
      write-dates-as-timestamps: false
      indent-output: true

eureka:
  client:
    enabled: false

logging:
  register-shutdown-hook: true
  file: ${user.home}/logs/${spring.application.name}.log
  level:
    root: INFO

server:
  http2:
    enabled: true
  compression:
    enabled: true
    mime-types: application/json,application/xml,text/html,text/xml,text/plain,text/css,application/javascript
    min-response-size: 2048

portal.developer.name: pksalagala
